DB_name = "yourName.crtai12tfp2w.us-east-2.rds.amazonaws.com" # Something similar to this
DB_user = "admin" # Something similar to this
DB_passwd = "123456" # Something similar to this
DB_cachehost = "yourName.crtai12tfp5w.us-east-2.rds.amazonaws.com" # Something similar to this
DB_port = "3306" # Something similar to this 
SecretKey= "YourfavoriteSecretKey" # Something similar to this
ACCESS_KEY = "AKMA5B8VZHFZIRZVLWZ" # Something similar to this
SECRET_ACCESS_KEY = "BRmtFDzsvKSRIab6QWJIP9onar5zvb69KhXcGRn8" # Something similar to this
API_KEY = "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" # Something similar to this